#!/usr/bin/dumb-init /bin/sh

set -e

case "$1" in
  help|--help|-h)
    echo "No help for you"
    exit 1
    ;;
  sh)
    /bin/sh
    ;;
  test)
    pip install safety
    safety check -r requirements.txt --full-report
    pip install pylint pylint_django
    pylint dtw api
    python /app/manage.py test
    ;;
  test_ci)
    pip install safety
    safety check -r requirements.txt --full-report
    pip install pylint pylint_django
    pylint dtw api
    python /app/manage.py test --exclude-tag=integration
    ;;
  devmode)
    python /app/manage.py runserver 0.0.0.0:8080
    ;;
  shell_plus)
    python /app/manage.py shell_plus
    ;;
  migrate)
    python /app/manage.py migrate
    ;;
  reset_db)
    python /app/manage.py reset_db --noinput
    ;;
  collectstatic)
    python /app/manage.py collectstatic --noinput
    ;;
  loaddata)
    python /app/manage.py loaddata api/fixtures/*
    ;;
  *)
    python /app/manage.py collectstatic --noinput
    gunicorn --bind :8080 --timeout 120 dtw.wsgi:application
    ;;
esac
