# Generated by Django 2.2.10 on 2020-02-09 21:59

import api.models.component
import api.models.schema
import api.models.workflow
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=128)),
                ('type', enumchoicefield.fields.EnumChoiceField(enum_class=api.models.component.ComponentTypeChoice, max_length=9)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=128)),
                ('args', django.contrib.postgres.fields.jsonb.JSONField()),
                ('version', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField()),
                ('type', enumchoicefield.fields.EnumChoiceField(enum_class=api.models.schema.SchemaTypeChoice, max_length=11)),
                ('name', models.CharField(max_length=128)),
                ('ebcdic', models.BooleanField(default=False)),
                ('format', enumchoicefield.fields.EnumChoiceField(enum_class=api.models.schema.SchemaFormatChoice, max_length=9)),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', enumchoicefield.fields.EnumChoiceField(enum_class=api.models.workflow.WorkflowTypeChoice, max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowJobConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.PositiveIntegerField()),
                ('job', models.PositiveIntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('step_number', models.PositiveIntegerField()),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField()),
                ('mappings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Component')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.Workflow')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowConnection',
            fields=[
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='connections', serialize=False, to='api.Workflow')),
                ('graph', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStepSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', enumchoicefield.fields.EnumChoiceField(enum_class=api.models.workflow.WorkflowStepSchemaTypeChoice, max_length=6)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Schema')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='api.WorkflowStep')),
            ],
        ),
    ]
