name: Test and Build Image

on:
  pull_request:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
       - bin/version
       - bin/test_ci
       - bin/build
