name: PR Builder

on:
  pull_request:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add +x to bin files
      run: |
        chmod +x ./bin/build
        chmod +x ./bin/test_ci
        chmod +x ./bin/version
    - name: Build Image
      run: |
       bin/build
    
    - name: Run Tests
      run: |
       bin/test_ci
       
    - name: Print Version
      run: |
       bin/version
